### ISSUE TITLE
Release new image to fix vulnerability

### ISSUE THREAD

**Issue by brumhard** [gardener/ingress-default-backend#18]
Hi there,

The latest release (0.9.0) does not contain all the dependency updates that have been integrated since then through dependabot.
Since for example pug 2.0.3 contains vulnerabilites (https://snyk.io/vuln/SNYK-JS-PUG-1071616) it would be great if you could just build a new image from the current master version to include the updates.

**Comment by brumhard** [comment]
@rfranzke could you have a look?

**Comment by rfranzke** [comment]
Done, here you go: https://github.com/gardener/ingress-default-backend/releases/tag/0.10.0
/close
